# Heart Attack

### Import Libaries

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score ,mean_squared_error

### Load Dataset

In [2]:
df = pd.read_csv(r"C:\Users\SRKT\Desktop\Data\HeartAttack.csv",na_values ="?")

In [3]:
df.head(10)

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1   29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2   29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0   
3   30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4   31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   
5   32    0   2     105.0  198.0  0.0      0.0    165.0    0.0      0.0   
6   32    1   2     110.0  225.0  0.0      0.0    184.0    0.0      0.0   
7   32    1   2     125.0  254.0  0.0      0.0    155.0    0.0      0.0   
8   33    1   3     120.0  298.0  0.0      0.0    185.0    0.0      0.0   
9   34    0   2     130.0  161.0  0.0      0.0    190.0    0.0      0.0   

   slope  ca  thal  num         
0    NaN NaN   NaN           0  
1    NaN NaN   NaN           0  
2    NaN NaN   NaN           0  
3    NaN NaN   6.0           0  
4    NaN NaN   NaN           0  
5    NaN NaN   NaN           0  
6    NaN NaN   NaN           0  
7    NaN NaN   NaN           0  
8    NaN NaN   NaN           0  
9    NaN NaN   NaN           0

In [4]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num       '],
      dtype='object')

In [5]:
df = df.rename(columns={"num       ":"target"})

In [6]:
df

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1     29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2     29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0   
3     30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4     31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...   
289   52    1   4     160.0  331.0  0.0      0.0     94.0    1.0      2.5   
290   54    0   3     130.0  294.0  0.0      1.0    100.0    1.0      0.0   
291   56    1   4     155.0  342.0  1.0      0.0    150.0    1.0      3.0   
292   58    0   2     180.0  393.0  0.0      0.0    110.0    1.0      1.0   
293   65    1   4     130.0  275.0  0.0      1.0    115.0    1.0      1.0   

     slope  ca  thal  target  
0      NaN NaN   NaN       0  
1      NaN NaN   NaN       0  
2      NaN NaN   NaN       0  
3      NaN NaN   6.0       0  
4      NaN NaN   NaN       0  
..     ...  ..   ...     ...  
289    NaN NaN   NaN       1  
290    2.0 NaN   NaN       1  
291    2.0 NaN   NaN       1  
292    2.0 NaN   7.0       1  
293    2.0 NaN   NaN       1  

[294 rows x 14 columns]

In [7]:
df["target"].value_counts(dropna= False)

0    188
1    106
Name: target, dtype: int64

In [8]:
len(df)

294

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       294 non-null    int64  
 1   sex       294 non-null    int64  
 2   cp        294 non-null    int64  
 3   trestbps  293 non-null    float64
 4   chol      271 non-null    float64
 5   fbs       286 non-null    float64
 6   restecg   293 non-null    float64
 7   thalach   293 non-null    float64
 8   exang     293 non-null    float64
 9   oldpeak   294 non-null    float64
 10  slope     104 non-null    float64
 11  ca        3 non-null      float64
 12  thal      28 non-null     float64
 13  target    294 non-null    int64  
dtypes: float64(10), int64(4)
memory usage: 32.3 KB


In [10]:
df = df.drop(columns=["slope","ca","thal"],axis =1)

In [11]:
df.head()

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0   28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1   29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2   29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0   
3   30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4   31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       294 non-null    int64  
 1   sex       294 non-null    int64  
 2   cp        294 non-null    int64  
 3   trestbps  293 non-null    float64
 4   chol      271 non-null    float64
 5   fbs       286 non-null    float64
 6   restecg   293 non-null    float64
 7   thalach   293 non-null    float64
 8   exang     293 non-null    float64
 9   oldpeak   294 non-null    float64
 10  target    294 non-null    int64  
dtypes: float64(7), int64(4)
memory usage: 25.4 KB


In [13]:
df = df.dropna().copy()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 261 entries, 0 to 293
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       261 non-null    int64  
 1   sex       261 non-null    int64  
 2   cp        261 non-null    int64  
 3   trestbps  261 non-null    float64
 4   chol      261 non-null    float64
 5   fbs       261 non-null    float64
 6   restecg   261 non-null    float64
 7   thalach   261 non-null    float64
 8   exang     261 non-null    float64
 9   oldpeak   261 non-null    float64
 10  target    261 non-null    int64  
dtypes: float64(7), int64(4)
memory usage: 24.5 KB


In [15]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
target      0
dtype: int64

In [20]:
df1 = pd.DataFrame([("bike","r_15"),
                    ("car","audi"),
                    ("bus","volvo"),
                    ("car","bmw"),
                    ("bike","pulsar")],columns = ("vechile","model"))

In [21]:
df1

vechile   model
0    bike    r_15
1     car    audi
2     bus   volvo
3     car     bmw
4    bike  pulsar

In [23]:
df1["map"] = [1,2,3,2,1]

In [24]:
df1

vechile   model  map
0    bike    r_15    1
1     car    audi    2
2     bus   volvo    3
3     car     bmw    2
4    bike  pulsar    1

In [25]:
pd.get_dummies(df1,columns=["vechile"])

model  map  vechile_bike  vechile_bus  vechile_car
0    r_15    1             1            0            0
1    audi    2             0            0            1
2   volvo    3             0            1            0
3     bmw    2             0            0            1
4  pulsar    1             1            0            0

In [27]:
df["cp"].value_counts(dropna =False)

4    113
2     92
3     46
1     10
Name: cp, dtype: int64

In [28]:
df["restecg"].value_counts(dropna =False)

0.0    208
1.0     47
2.0      6
Name: restecg, dtype: int64

In [29]:
df = pd.get_dummies(df, columns=["cp","restecg"])

In [30]:
df.head()

age  sex  trestbps   chol  fbs  thalach  exang  oldpeak  target  cp_1  \
0   28    1     130.0  132.0  0.0    185.0    0.0      0.0       0     0   
1   29    1     120.0  243.0  0.0    160.0    0.0      0.0       0     0   
3   30    0     170.0  237.0  0.0    170.0    0.0      0.0       0     1   
4   31    0     100.0  219.0  0.0    150.0    0.0      0.0       0     0   
5   32    0     105.0  198.0  0.0    165.0    0.0      0.0       0     0   

   cp_2  cp_3  cp_4  restecg_0.0  restecg_1.0  restecg_2.0  
0     1     0     0            0            0            1  
1     1     0     0            1            0            0  
3     0     0     0            0            1            0  
4     1     0     0            0            1            0  
5     1     0     0            1            0            0

In [33]:
numeric_cols = ["age","trestbps","chol","thalach","oldpeak"]
cat_cols = list(set(df.columns)-set(numeric_cols)-{"target"})

In [32]:
df["oldpeak"].value_counts(dropna =False)

0.0    165
1.0     36
2.0     28
1.5     15
3.0      9
2.5      3
0.5      2
0.8      1
5.0      1
4.0      1
Name: oldpeak, dtype: int64

In [35]:
cat_cols , numeric_cols

(['cp_4',
  'restecg_1.0',
  'cp_1',
  'fbs',
  'cp_2',
  'restecg_0.0',
  'sex',
  'exang',
  'cp_3',
  'restecg_2.0'],
 ['age', 'trestbps', 'chol', 'thalach', 'oldpeak'])

In [37]:
df_train ,df_test = train_test_split(df,test_size = 0.2,stratify =df["target"])

In [42]:
df["target"].value_counts(dropna = True)

0    163
1     98
Name: target, dtype: int64

In [38]:
df_train.shape , df_test.shape

((208, 16), (53, 16))

In [39]:
df_train["target"].value_counts()

0    130
1     78
Name: target, dtype: int64

In [45]:

#scaler.fit(df_train[numeric_cols])

def get_feature_target(df,numeric_cols,cat_cols):
    scaler = StandardScaler()
    x_numeric = scaler.fit_transform(df[numeric_cols])
    x_cat = df[cat_cols].to_numpy()
    x = np.hstack((x_numeric,x_cat))
    y = df["target"]
    
    return x,y  

In [47]:
x_train , y_train = get_feature_target(df_train,numeric_cols,cat_cols)

In [53]:
x_train.shape  , y_train.shape

((208, 15), (208,))

In [54]:
clf = LogisticRegression()
clf.fit(x_train,y_train)

LogisticRegression()

In [56]:
clf.intercept_, clf.coef_[0]

(array([-1.99133731]),
 array([-0.1661014 , -0.02133314,  0.45625149, -0.18541572,  1.14412316,
         0.63668969,  0.01983997,  0.34259835,  1.08075716, -1.0434696 ,
         0.27870445,  1.07587273,  0.98649609,  0.06471736, -0.29800862]))

In [57]:
x_test , y_test = get_feature_target(df_test,numeric_cols,cat_cols)

In [58]:
y_pred = clf.predict(x_test)

In [59]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [61]:
accuracy_score(y_test,y_pred)

0.8113207547169812

In [63]:
mean_squared_error(y_test,y_pred)

0.18867924528301888